### ISSUE TITLE
Manifest Request Reduction

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#127]
* [ ] In settings add a `enforcement` setting, defaults to `true` (read on).
* [ ] Have the manifest download if its missing.
* [ ]  Check the total size of the manifest against the server.
  - acts as a signature
  - or just ~~MD5-Hash~~ SHA1 check it.
* [ ] Check that signature
* [ ] If it matches, precede with normal checkup.
  - If the user has `enforcement` off dont do anything.
  - **6MB DL saved!**
* [ ] if not download a new manifest.
  - If  `enforcement` is off prompt the user for action, to allow or disallow checkup.

**Comment by adrianojn** [comment]
Try gzip the manifet.

    6.3M  ygopro.json
    294k  ygopro.gz

**Comment by Zayelion** [comment]
`doh!` Check to see it was gzipped?
