### ISSUE TITLE
Stardust Warrior

### ISSUE THREAD

**Issue by Starstrike** [SalvationDevelopment/YGOPro-Support-System#136]
When Stardust Warrior leaves the field by a card effect, the effect to special summon a level 8 or lower "Warrior" Synchro Monster does not come up accurately. 

Situation occurred when Stardust Warrior was destroyed by a Ryko while I had Road Warrior in my extra deck. I did not get the option to summon him at all.

His effect also cannot miss timing as it is a "if..you can..." effect.

**Comment by Zayelion** [comment]
verification this is fixed?
