### ISSUE TITLE
Thumbs.db error

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#137]
http://puu.sh/e32MT/da75f9b1f5.png

**Comment by adrianojn** [comment]
*Thumbs.db* should be removed or blacklisted.

**Comment by Zayelion** [comment]
Its automatically generated by the operating system while we are using the server anytime the `/pics/` folder is opened with `explorer.exe` so have to add code to `update.js` to blacklist it. Also while we are at it update needs to be changed so it works from update.js and runs on a file update listener or update scheduler.

**Comment by adrianojn** [comment]
You can disable it: http://www.computerhope.com/issues/ch001061.htm

**Comment by Zayelion** [comment]
fix applied
