### ISSUE TITLE
Noble Knights OCG

### ISSUE THREAD

**Issue by adrianojn** [SalvationDevelopment/YGOPro-Support-System#139]
- Merlin
- Noble Knight Bedwyr
- Last Chapter of the Noble Knights

...should be marked as TCG/OCG: [Epic of Noble Knights: Holy Sword of Guidance](http://yugioh.wikia.com/wiki/Duel_Field_EX_Epic_of_Noble_Knights:_Holy_Sword_of_Guidance)

**Comment by Zayelion** [comment]
updated
