### ISSUE TITLE
Ygopro not working

### ISSUE THREAD

**Issue by zeak6464** [SalvationDevelopment/YGOPro-Support-System#146]
http://s13.postimg.org/xqo075vl3/screenshot_24.png

http://s13.postimg.org/p9ohw8qw7/screenshot_25.png

Launcher does work tho

**Comment by Zayelion** [comment]
Those look like permission issues.

**Comment by Zayelion** [comment]
http://s13.postimg.org/5gce3jdif/screenshot_26.png

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/YGOPro-Support-System/commit/e855a93ff023dd66de826dd3b523987382c26b9e

**Comment by Zayelion** [comment]
http://s13.postimg.org/fexcq0mxz/screenshot_27.png

**Comment by Zayelion** [comment]
abandoning mac
