### ISSUE TITLE
OCG List error

### ISSUE THREAD

**Issue by 0mniMage** [SalvationDevelopment/YGOPro-Support-System#162]
http://prntscr.com/60fyjz

Exodia's head is missing from the most recent OCG F/L list (2015.1.1)

http://www.yugioh-card.com/my/event/forbidden.php?list=201501&lang=en Proof that it's limited in OCG.

**Comment by Zayelion** [comment]
You know Karl did the update.....

**Comment by GuybrushThreepwoodSD** [comment]
Based off existing files, yes. I didn't change anything about exodia's head from one list to another, to my knowledge.

**Comment by ChibiChanNya** [comment]
2 minute fix, better than bickering about it nya :p
