### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by adrianojn** [SalvationDevelopment/YGOPro-Support-System#164]
Image:
* 58016954 Jesshaddoll - Zefra Naga

Thumbnail:
* 34492631 Junk Giant
* 81983656 Blackwing Tamer - Hawk Joe the Jet
* 96163807 Tristan, Knight of the Underworld

Field:
* 32354768 Oracle of the Zefra
* 57554544 Fire King's Island
* 84171830 The True Monarch Dominion

For future reference: https://github.com/adrianojn/checkmissing/releases

**Comment by Zayelion** [comment]
Planning to make something to run all the wonderful tools you built us on the hour or nightly. I'll pass this off to Chibi and Zets.

**Comment by Zetsuei** [comment]
I Intend to see this finished today

**Comment by ChibiChanNya** [comment]
Credits to Zetsuei, got all the pics now ya. Thankies
