### ISSUE TITLE
Switch to YGOPro-FH

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#170]

**Comment by adrianojn** [comment]
reason?

**Comment by Zayelion** [comment]
Community unification primarily. YGOPro 'belongs' to FH. Percy, DevPro, TDOANE, and Salvation are using ill forked variants. Sid is pushing more to mainline all the features implemented in the other systems are listed on the "whishlist" of the ygopro wiki wishlist. I feel FH is just being negligent and we as developers around the project are acting in bad faith.

**Comment by Zayelion** [comment]
Change of plans, going to just re-implement the client browser side.
