### ISSUE TITLE
remake linux tarball

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#172]

**Comment by adrianojn** [comment]
new binary: https://drive.google.com/file/d/0BydAR5G15GTEUDhVTXJkLTVGSDA/view?usp=sharing

ocgcore updated until https://github.com/Fluorohydride/ygopro/commit/d9450db

shuffle button added: https://gist.github.com/adrianojn/be5ff9254736f62eecfe

**Comment by Zayelion** [comment]
Wait wait wait... you can program in C++ for merges? If so I have laundry list of stuff that needs to be done against FH-'s mainline.

**Comment by Zayelion** [comment]
When A2 updates the Windows binary and server side ocgcore.dll I'll deploy these.

**Comment by adrianojn** [comment]
> you can program in C++ for merges?
yes
