### ISSUE TITLE
Bluffs

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#224]
https://github.com/sidschingis/Dev_ygopro/commit/4197e04b1249c5dd7cb0574401a10b1cbc2a5709

**Comment by Zayelion** [comment]
Some bugs where noticed, I think we should shelf this.

**Comment by adrianojn** [comment]
the bug may be related to https://github.com/sidschingis/Dev_ygopro/commit/404ab191abdd14c19be7c353d2e02c142007b1b9
