### ISSUE TITLE
AI responses

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#227]
* [x]  "CTOS_RESPONSE",
 * [x]  "CTOS_UPDATE_DECK",
 * [x]  "CTOS_HAND_RESULT",
 * [x] "CTOS_TP_RESULT",
 * [x] "CTOS_PLAYER_INFO",
 *  "CTOS_CREATE_GAME",
 *  "CTOS_JOIN_GAME",
 * [x] "CTOS_LEAVE_GAME",
 * [x] "CTOS_SURRENDER",
 * [ ] "CTOS_TIME_COMFIRM",
 * [x] "CTOS_CHAT",
 * [x]  "CTOS_HS_TODUELIST",
 * [x] "CTOS_HS_TOOBSERVER", //to observer
 * [x] "CTOS_HS_READY",
 * [x] "CTOS_HS_NOTREADY",
 * [x] "CTOS_HS_KICK",
 * [x]  "CTOS_HS_START"

https://github.com/Fluorohydride/ygopro/blob/25bdab4c6d0000f841aee80c11cbf2e95ee54047/gframe/network.h

These network responses need to be recreated in Javascript. The structure is line by line an array of buffere memory appended with the two byte length then 1 byte CTOS command. For example 

CTOS_PlayerInfo
 [len, len, CTOS_PLAYER_INFO, U, S ,E, R, N, A, M, E]

**Comment by Zayelion** [comment]
https://github.com/Fluorohydride/ygopro/blob/master/gframe/duelclient.cpp#L103 This function needs to be recreated for the ai

**Comment by Zayelion** [comment]
I dont understand how CTOS_LEAVE_GAME is being used.

**Comment by adrianojn** [comment]
1. to spectators leave the game
2. to players leave the join game window ([network.h](https://github.com/Fluorohydride/ygopro/blob/master/gframe/network.h#L200-L203)).

**Comment by Zayelion** [comment]
And what about `CTOS_TIME_COMFIRM`. I am going to skip `CTOS_CREATE_GAME` and `CTOS_JOIN_GAME` I'm dropping the current replay implementation, and I I'll experiment with `CTOS_CREATE_GAME` later to see if it replaces the roompass system.

**Comment by adrianojn** [comment]
CTOS_TIME_CO**N**FIRM
used for skipping the time where the opponent is confirming a action ([single_duel.cpp](https://github.com/Fluorohydride/ygopro/blob/master/gframe/single_duel.cpp#L1323-L1346))

**Comment by Zayelion** [comment]
So do I just set an interval and send it to the server when the player is idle? Or continuously?
