### ISSUE TITLE
Recompiles for Launcher

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#230]
* [x] @Zayelion installer, update nwjs, update installer, installer installer harness to server
* [x] @A2152225 recompile for windows
* [ ] @IngwiePhoenix recompile for Mac
* [x] @adrianojn recompile for Linux
* [x] Version number increased.

**Comment by adrianojn** [comment]
https://drive.google.com/file/d/0BydAR5G15GTEUDhVTXJkLTVGSDA/view?usp=sharing

**Comment by A2152225** [comment]
Client Recompiled with card verification change

**Comment by Zayelion** [comment]
Gonna flag mac seg fault fix for bounty.
