### ISSUE TITLE
Linux 64

### ISSUE THREAD

**Issue by adrianojn** [SalvationDevelopment/YGOPro-Support-System#236]
I saw  users demanding a 64-bit version on forum. Since Travis-CI runs Ubuntu 64-bit we can use it as build machine.

1. The binary name will be `appication_ygopro64`
2. A new folder `lib64` will be used to store the  dynamic libraries (event, Irrlicht, freetype etc).
3. I'm not sure if `libocgcore.so` will work as dynamic library.
4. I'm not sure if MP3 audio will work.

**Comment by adrianojn** [comment]
first build: [linux64.tgz](https://github.com/adrianojn/ygopro-salvation-custom/releases/download/v1.033.4-build2/linux64.tgz)

```js
if (operating_system === 'linux' && os.arch() === 'x64') {
	executable = './application_ygopro64'
}
```

**Comment by ekaomk** [comment]
Hi Fluorohydride. i want to know how to compile libocgcore.so (Shared library) on linux.
I try compiled and that has 8.40 Mb and use it. and i found problem when run the YGOCore server.

This is error message.
"mono: symbol lookup error: /root/YGOPro-Server/libocgcore.so: undefined symbol: luaL_newstate"

http://upic.me/i/js/9capture.png

Please tell me how to compile libocgcore to work with linux server.
Please...

Thanks in advance. and so sorry for my bad English.

**Comment by adrianojn** [comment]
You need to add `linkoptions { "-llua" }` to the end of `ocgcore/premake4.lua`

**Comment by ekaomk** [comment]
not work. same error message. what your lua lib version?

**Comment by adrianojn** [comment]
lua 5.2
Remember to remove **all** files in the `bin` folder before compiling.

**Comment by ekaomk** [comment]
Not work again. now i don't know what to do next. I still have 8 Mb libocgcore.so and that not work.
This is my step (by step) for build libocgcore.so. please check it.i worry about this.
1) First. i have ubuntu 14.04 with default config and kernel.
2) I ran update command "sudo apt-get update" and that successfully.
3) I install some packages require for compile libocgcore.so by this command
"sudo apt-get -y install build-essential git premake4 liblua5.2-dev"
and that successfully.
4) I clone ygocore on git of "Fluorohydride" by this command.
"git clone https://github.com/Fluorohydride/ygopro.git"
5) I edit file "ygopro/ocgcore/premake4.lua" by
5.1) change kind "StaticLib" to kind "SharedLib"
5.2) add "-llua" to buildoptions (buildoptions { "-std=gnu++0x", "-llua" })
6) I go to folder ygopro by "cd ygopro"
7) I ran make command "premake4 gmake" and that successfully.
8) Final. i build libocgcore.so by this command.
"make config=release ocgcore -C build"

And i get the libocgcore.so with 8 Mb and error message after scissors, paper and rocks game.
"mono: symbol lookup error: /root/YGOPro-Server/libocgcore.so: undefined symbol: luaL_newstate"

Please. help me. i have no idea about this. but i must to do it. i search and do this for 2 day ago.
Thanks in advance again. and so sorry for my bad English.

**Comment by adrianojn** [comment]
First do a `make clean`

> 5.2) add "-llua" to buildoptions (buildoptions { "-std=gnu++0x", "-llua" })

No. **Add** to the end of file like this: https://github.com/Buttys/ygopro/blob/master/ocgcore/premake4.lua#L11

**Comment by ekaomk** [comment]
It has error on linking.

------------------------------------------------------------------------------------------

Linking ocgcore
/usr/bin/ld: cannot find -llua
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/release/libocgcore.so] Error 1
make: *** [ocgcore] Error 2
make: Leaving directory `/home/ubuntu/workspace/ygopro/build'

------------------------------------------------------------------------------------------

cannot find -llua? What it that. i have installed lua 5.2. but why?

**Comment by adrianojn** [comment]
The library name on Ubuntu is inconsistent. Try `-llua52` or `-llua5.2`

**Comment by ekaomk** [comment]
i think it too close. the error has change to.
----------------------------------------------------------------
[Log] Unable to load config.txt, using default settings.
[Log] Accepting client version 0x1332 or better.
[Error] System.DllNotFoundException: ocgcore
  at (wrapper managed-to-native) OcgWrapper.Api:set_card_reader (OcgWrapper.Api/CardReader)
  at OcgWrapper.Api.Init (System.String path, System.String scripts, System.String cards) [0x00000] in <filename unknown>:0 
  at YGOCore.Server.Start (Int32 port) [0x00000] in <filename unknown>:0 
----------------------------------------------------------------

**Comment by adrianojn** [comment]
> [Error] System.DllNotFoundException: ocgcore

check http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

**Comment by Zayelion** [comment]
I'll make a note to add all this to the `readme.md` later on.

**Comment by ekaomk** [comment]
not work... again. and i tired.

================================================================
root@ubuntu:/home/server# ldconfig -p |grep libocgcore
        libocgcore.so (libc6,x86-64) => /usr/local/lib/libocgcore.so
================================================================

that look OK. but not work. still got same error.

where can i contact you? any social network. e-mail?
i need your help.

**Comment by adrianojn** [comment]
look for *adrianosoaresjn* on Skype

`libocgcore.so` should be in the same folder as ygocore.exe
