### ISSUE TITLE
Translate to Portuguese 

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Support-System#242]
@adrianojn https://github.com/SalvationDevelopment/YGOPro-Support-System/blob/master/server/http/js/translations.js
Could you fill out the pt lines for this?

**Comment by AlexHoQuan** [comment]
I do not speak portuguese

**Comment by westcoastkiwi** [comment]
It wasn't assigned to you. It was assigned to Adriano.
