### ISSUE TITLE
My upcoming "rampage"

### ISSUE THREAD

**Issue by IngwiePhoenix** [SalvationDevelopment/YGOPro-Support-System#98]
So... First, hey everyone of the team. I did not know where to put this, but maybe that one here should do.

As of the 18th, I will have a winter break from school. That means that I can dedicate my time to coding - to both my own and SalvationDev's projects. But what will that be? I thought to announce what I am planning first. So here goes:

- Create a branch to restructure the source tree.
    * Binaries in git? That's a strict no-go. These clutter up the git object tree and in general are hard to diff upon... Instead, I will be adding a shell script to download required binaries (namely node-webkit, probably)
- Create a script to bundle launcher AND app into a single .app bundle under Mac OS X.
- Change the YGOPro source tree from using premake to CMake.
    * Irrlicht is NOT EASY to be compiled under OS X. You have to know the tricks and bits to do so. A note or proper fix should be added.
    * Libraries like libevent and other dependencies are not available by default but could properly be noted down either within the README or when CMake fails - aka. better error reporting.
    * Add a "build target" to prepare a release, to download assets, and the like.

I am thus planning further code cleanup on YGOPro and to use FLTK instead of "gframe": https://groups.google.com/forum/#!topic/fltkgeneral/rbrPEo6bQWw

FLTK is a cross-platform window/widget toolkit. Thru it, I plan to re-implement OCGCore with a new GUI. More cross-platform, better structured, simply said: make it a round thing there.

I may come along other/newer plans. Therefore I would simply suggest to see this issue if I add to it. Untill then, you can give me suggestions.

Oh, besides. I am going to prepare my server to be running a continious integration, thus making the same on my **Mac Mini homeserver**. Both can then push releases to my upcoming company site http://ingwie.io . I am still writing on it and should release a flat version of it soon. (flat = very basic)

Having buidlbots for Linux and mac shoudl be helpful, since most of the team are Windows users. I, however, have access and am daily using Mac, thus having a rather powerful linux box within an OVH DC. ^^ That, in my opinion, should help with "dev releases"...aka, tarballs of per-commit distributions.

I hope you dont mind these plans and feel free to add to it!

Kind regards, Ingwie.

PS: I originally wanted to make the YGOPro/FLTK combo about half a year ago, but never could move myself to do so. Now I have valid reason to move it. :)

**Comment by Zayelion** [comment]
Winter break is almost over.
* [x] [The NAPI](https://github.com/SalvationDevelopment/YGOPro-NAPI-Interface) is in a seperate git now. 
* [ ] We still dont have a deploy for Mac.
* [x] The mac application is deployed in the updater 
* [x] A number of binaries have been removed from the git, specifically the server folder. I dont feel the server and client should be split into seperate gits at this time because the client requires the server to be developed on locally. This will become increasingly true as new features are added and the system as a whole makes the crawl to the web.
